(print (isinstance 'd str))
(print (isinstance "a" str))
(print (isinstance 0 int))
(print (isinstance 1 float))
(print (isinstance 1.2 float))
(print (isinstance 'asdf symbol))
(print "")

(print (type t))
(print (type nil))
