(print (isinstance 'd str))
(print (isinstance "a" str))
(print (isinstance 0 int))
(print (isinstance 1 float))
(print (isinstance 1.2 float))
(print (isinstance 'asdf symbol))
(print "")

(print (type t))
(print (type nil))
(print (type '()))
(print (isinstance '() list))
(print (isinstance () list))
(print (isinstance nil list))
(print "")

(print (eq () ()))
(print (== () ()))
(print (== () nil))
(print "")

(print (bool ""))
(print (bool ()))
(print (bool 0))
(print (bool 0.1))
(print (bool 0.0))
(print)

(print (isinstance 1 number))
(print (isinstance 1.3 number))
(print (isinstance -1.0 number))
